language: php
php:
  - 5.4

before_script:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpunit --stderr --configuration phpunit.xml
  - phpcs --standard=PEAR --extensions=php $PWD/src